<a href="https://colab.research.google.com/github/Eesha00/tensorflow-deep-learning-exercises/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # find the version number (should be 2.x+)

2.19.0


In [3]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(1)
scalar # An empty tuple ()
         #indicates that it's a scalar (a single value with no dimensions)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector
#output:shape=(2,):
#It means the tensor is a 1-dimensional array (a vector) with 2 elements.
# The number inside the parentheses indicates the size of that dimension.
# If it were a 2x2 matrix, the shape would be (2, 2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector = tf.constant([10,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  2,  3], dtype=int32)>

In [7]:
vector.ndim


1

In [8]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [10]:
# Won't error
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [3]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [5]:
tf.ones(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [6]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [7]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [8]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [9]:
X = tf.constant([[3,4,1],
                [1,2,3]])
Y = tf.constant([[1],
                 [2],
                 [3]])
X@Y

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14],
       [14]], dtype=int32)>

In [11]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(tf.transpose(Y), tf.transpose(X))

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[14, 14]], dtype=int32)>

In [16]:
import numpy as np
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=10))
E

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([45,  1, 45, 34, 48, 19, 79,  3, 53,  1])>

In [17]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [19]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [20]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

In [21]:
some_list = [1,2,3,4]
tf.one_hot(some_list, depth = 3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [22]:
A = tf.constant([[1, 2],
                 [3, 4]])
B = tf.constant([[5, 6],
                 [7, 8]])

# Perform matrix dot multiplication
C = tf.matmul(A, B)
print("Matrix A:\n", A.numpy())
print("Matrix B:\n", B.numpy())
print("Result of A . B:\n", C.numpy())

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Result of A . B:
 [[19 22]
 [43 50]]


In [24]:
vector1 = tf.constant([1, 2, 3])
vector2 = tf.constant([4, 5, 6])

# Calculate the dot product using tf.tensordot
# For two 1D vectors, tensordot with axes=1 performs the dot product
dot_product_tensordot = tf.tensordot(vector1, vector2, axes=1)

print("Vector 1:", vector1.numpy())
print("Vector 2:", vector2.numpy())
print("Dot Product (tf.tensordot):", dot_product_tensordot.numpy())

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Dot Product (tf.tensordot): 32


In [25]:
scalar_tensor = tf.constant(42)
vector_tensor = tf.constant([1, 2, 3, 4])
matrix_tensor = tf.constant([[5, 6], [7, 8]])
general_tensor = tf.constant([[[10, 11], [12, 13]], [[14, 15], [16, 17]]])

print("Scalar Tensor:", scalar_tensor)
print("Vector Tensor:", vector_tensor)
print("Matrix Tensor:", matrix_tensor)
print("General Tensor (Rank 3):", general_tensor)

Scalar Tensor: tf.Tensor(42, shape=(), dtype=int32)
Vector Tensor: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Matrix Tensor: tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
General Tensor (Rank 3): tf.Tensor(
[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]], shape=(2, 2, 2), dtype=int32)
