<a href="https://colab.research.google.com/github/Eesha00/tensorflow-deep-learning-exercises/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # find the version number (should be 2.x+)

2.19.0


In [3]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(1)
scalar # An empty tuple ()
         #indicates that it's a scalar (a single value with no dimensions)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector
#output:shape=(2,):
#It means the tensor is a 1-dimensional array (a vector) with 2 elements.
# The number inside the parentheses indicates the size of that dimension.
# If it were a 2x2 matrix, the shape would be (2, 2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector = tf.constant([10,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  2,  3], dtype=int32)>

In [7]:
vector.ndim


1

In [8]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [10]:
# Won't error
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>